server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:3000"
            allowed-headers: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
            allow-credentials: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: membre-service
          uri: lb://membre-service
          predicates:
            - Path=/membres/**
        - id: collaboration-service
          uri: lb://collaboration-service
          predicates:
            - Path=/collaborations/**
        - id: team-service
          uri: lb://team-service
          predicates:
            - Path=/teams/**
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/auth/**
            - Method=POST
        - id: discovery-service
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
logging:
  level:
    org:
      springframework:
        security: DEBUG